name: Runs open rewrite

on:
  workflow_call:
    secrets:
      SOME_SECRET:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
          cache: maven
      - name: download recipe file
        shell: bash
        run: |
          wget https://raw.githubusercontent.com/luizleiteoliveira/tutorials/main/.github/workflows/rewrite.yml
      - name: look
        shell: bash
        run: |
          ls
      - name: Build with Maven
        id: mvn-dryRun
        run: mvn rewrite:dryRun
      - name: Validar se tem atualizaçoes a serem feitas
        run: |
          if echo ${{ steps.mvn-dryRun.outputs.stdout }} | grep -q "[WARNING] These recipes would make changes to"; then
            echo "::warning ::Changes to be made"
          else
            echo "Project is on right track and fully updated"
          fi
        env:
          OUTPUT: ${{ steps.maven-build.outputs.stdout }}