name: Runs open rewrite

on:
  workflow_call:
    secrets:
      SOME_SECRET:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
          cache: maven
      - name: look
        shell: bash
        run: |
          ls
      - name: Build with Maven
        run: mvn rewrite:dryRun